// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clause_analyses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClauseAnalysis = `-- name: CreateClauseAnalysis :one
INSERT INTO clause_analyses (id, clause_id, risk_level, explanation, ambiguous_language, recommendations, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, clause_id, risk_level, explanation, ambiguous_language, recommendations, status
`

type CreateClauseAnalysisParams struct {
	ID                string
	ClauseID          string
	RiskLevel         pgtype.Text
	Explanation       pgtype.Text
	AmbiguousLanguage pgtype.Text
	Recommendations   pgtype.Text
	Status            string
}

func (q *Queries) CreateClauseAnalysis(ctx context.Context, arg CreateClauseAnalysisParams) (ClauseAnalysis, error) {
	row := q.db.QueryRow(ctx, createClauseAnalysis,
		arg.ID,
		arg.ClauseID,
		arg.RiskLevel,
		arg.Explanation,
		arg.AmbiguousLanguage,
		arg.Recommendations,
		arg.Status,
	)
	var i ClauseAnalysis
	err := row.Scan(
		&i.ID,
		&i.ClauseID,
		&i.RiskLevel,
		&i.Explanation,
		&i.AmbiguousLanguage,
		&i.Recommendations,
		&i.Status,
	)
	return i, err
}

const getAnalysesByContract = `-- name: GetAnalysesByContract :many
SELECT ca.id, ca.clause_id, ca.risk_level, ca.explanation, ca.ambiguous_language, ca.recommendations, ca.status
FROM clause_analyses ca
JOIN clauses c ON c.id = ca.clause_id
WHERE c.contract_id = $1
`

func (q *Queries) GetAnalysesByContract(ctx context.Context, contractID string) ([]ClauseAnalysis, error) {
	rows, err := q.db.Query(ctx, getAnalysesByContract, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClauseAnalysis
	for rows.Next() {
		var i ClauseAnalysis
		if err := rows.Scan(
			&i.ID,
			&i.ClauseID,
			&i.RiskLevel,
			&i.Explanation,
			&i.AmbiguousLanguage,
			&i.Recommendations,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
