// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clauses.sql

package db

import (
	"context"
)

const createClause = `-- name: CreateClause :one
INSERT INTO clauses (id, contract_id, sequence_number, text)
VALUES ($1, $2, $3, $4)
RETURNING id, contract_id, sequence_number, text
`

type CreateClauseParams struct {
	ID             string
	ContractID     string
	SequenceNumber int32
	Text           string
}

func (q *Queries) CreateClause(ctx context.Context, arg CreateClauseParams) (Clause, error) {
	row := q.db.QueryRow(ctx, createClause,
		arg.ID,
		arg.ContractID,
		arg.SequenceNumber,
		arg.Text,
	)
	var i Clause
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.SequenceNumber,
		&i.Text,
	)
	return i, err
}

const getClausesByContract = `-- name: GetClausesByContract :many
SELECT id, contract_id, sequence_number, text FROM clauses WHERE contract_id = $1 ORDER BY sequence_number
`

func (q *Queries) GetClausesByContract(ctx context.Context, contractID string) ([]Clause, error) {
	rows, err := q.db.Query(ctx, getClausesByContract, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Clause
	for rows.Next() {
		var i Clause
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.SequenceNumber,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
