// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contracts.sql

package db

import (
	"context"
)

const createContract = `-- name: CreateContract :one
INSERT INTO contracts (id, filename, raw_text, status)
VALUES ($1, $2, $3, $4)
RETURNING id, filename, raw_text, status, created_at, requires_review
`

type CreateContractParams struct {
	ID       string
	Filename string
	RawText  string
	Status   string
}

func (q *Queries) CreateContract(ctx context.Context, arg CreateContractParams) (Contract, error) {
	row := q.db.QueryRow(ctx, createContract,
		arg.ID,
		arg.Filename,
		arg.RawText,
		arg.Status,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.RawText,
		&i.Status,
		&i.CreatedAt,
		&i.RequiresReview,
	)
	return i, err
}

const createContractWithOptions = `-- name: CreateContractWithOptions :one
INSERT INTO contracts (id, filename, raw_text, status, requires_review)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, filename, raw_text, status, created_at, requires_review
`

type CreateContractWithOptionsParams struct {
	ID             string
	Filename       string
	RawText        string
	Status         string
	RequiresReview bool
}

func (q *Queries) CreateContractWithOptions(ctx context.Context, arg CreateContractWithOptionsParams) (Contract, error) {
	row := q.db.QueryRow(ctx, createContractWithOptions,
		arg.ID,
		arg.Filename,
		arg.RawText,
		arg.Status,
		arg.RequiresReview,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.RawText,
		&i.Status,
		&i.CreatedAt,
		&i.RequiresReview,
	)
	return i, err
}

const getContract = `-- name: GetContract :one
SELECT id, filename, raw_text, status, created_at, requires_review FROM contracts WHERE id = $1
`

func (q *Queries) GetContract(ctx context.Context, id string) (Contract, error) {
	row := q.db.QueryRow(ctx, getContract, id)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.RawText,
		&i.Status,
		&i.CreatedAt,
		&i.RequiresReview,
	)
	return i, err
}

const updateContractStatus = `-- name: UpdateContractStatus :exec
UPDATE contracts SET status = $2 WHERE id = $1
`

type UpdateContractStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateContractStatus(ctx context.Context, arg UpdateContractStatusParams) error {
	_, err := q.db.Exec(ctx, updateContractStatus, arg.ID, arg.Status)
	return err
}

const updateContractText = `-- name: UpdateContractText :exec
UPDATE contracts SET raw_text = $2 WHERE id = $1
`

type UpdateContractTextParams struct {
	ID      string
	RawText string
}

func (q *Queries) UpdateContractText(ctx context.Context, arg UpdateContractTextParams) error {
	_, err := q.db.Exec(ctx, updateContractText, arg.ID, arg.RawText)
	return err
}
