// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Clause struct {
	ID             string
	ContractID     string
	SequenceNumber int32
	Text           string
}

type ClauseAnalysis struct {
	ID                string
	ClauseID          string
	RiskLevel         pgtype.Text
	Explanation       pgtype.Text
	AmbiguousLanguage pgtype.Text
	Recommendations   pgtype.Text
	Status            string
}

type Contract struct {
	ID        string
	Filename  string
	RawText   string
	Status    string
	CreatedAt pgtype.Timestamptz
}

type Review struct {
	ID         string
	ClauseID   string
	Decision   string
	Annotation pgtype.Text
}

type Summary struct {
	ID         string
	ContractID string
	Content    string
	CreatedAt  pgtype.Timestamptz
}
