// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentRun struct {
	ID          string
	ClauseID    string
	RunID       pgtype.Text
	Status      string
	StepCount   int32
	UsedTokens  int32
	UsedCostUsd pgtype.Numeric
	StartedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
}

type AgentStep struct {
	ID           string
	AgentRunID   string
	StepIndex    int32
	MessagesJson []byte
	UsageJson    []byte
	CreatedAt    pgtype.Timestamptz
}

type Clause struct {
	ID             string
	ContractID     string
	SequenceNumber int32
	Text           string
}

type ClauseAnalysis struct {
	ID                string
	ClauseID          string
	RiskLevel         pgtype.Text
	Explanation       pgtype.Text
	AmbiguousLanguage pgtype.Text
	Recommendations   pgtype.Text
	Status            string
}

type ClauseLibrary struct {
	ID           string
	ClauseType   string
	StandardText string
	Notes        string
}

type Contract struct {
	ID             string
	Filename       string
	RawText        string
	Status         string
	CreatedAt      pgtype.Timestamptz
	RequiresReview bool
}

type Review struct {
	ID         string
	ClauseID   string
	Decision   string
	Annotation pgtype.Text
}

type Run struct {
	ID           string
	ContractID   string
	StartedAt    pgtype.Timestamptz
	EndedAt      pgtype.Timestamptz
	Status       string
	ReachedStage pgtype.Text
}

type Summary struct {
	ID         string
	ContractID string
	Content    string
	CreatedAt  pgtype.Timestamptz
}
