// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (id, clause_id, decision, annotation)
VALUES ($1, $2, $3, $4)
RETURNING id, clause_id, decision, annotation
`

type CreateReviewParams struct {
	ID         string
	ClauseID   string
	Decision   string
	Annotation pgtype.Text
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ID,
		arg.ClauseID,
		arg.Decision,
		arg.Annotation,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ClauseID,
		&i.Decision,
		&i.Annotation,
	)
	return i, err
}

const getReviewsByContract = `-- name: GetReviewsByContract :many
SELECT r.id, r.clause_id, r.decision, r.annotation
FROM reviews r
JOIN clauses c ON c.id = r.clause_id
WHERE c.contract_id = $1
`

func (q *Queries) GetReviewsByContract(ctx context.Context, contractID string) ([]Review, error) {
	rows, err := q.db.Query(ctx, getReviewsByContract, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ClauseID,
			&i.Decision,
			&i.Annotation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
