// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summaries.sql

package db

import (
	"context"
)

const getSummaryByContract = `-- name: GetSummaryByContract :one
SELECT id, contract_id, content, created_at FROM summaries WHERE contract_id = $1
`

func (q *Queries) GetSummaryByContract(ctx context.Context, contractID string) (Summary, error) {
	row := q.db.QueryRow(ctx, getSummaryByContract, contractID)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSummary = `-- name: UpsertSummary :one
INSERT INTO summaries (id, contract_id, content)
VALUES ($1, $2, $3)
ON CONFLICT (contract_id) DO UPDATE SET content = EXCLUDED.content
RETURNING id, contract_id, content, created_at
`

type UpsertSummaryParams struct {
	ID         string
	ContractID string
	Content    string
}

func (q *Queries) UpsertSummary(ctx context.Context, arg UpsertSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, upsertSummary, arg.ID, arg.ContractID, arg.Content)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
